[package]
name = "ping"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
pcap = "2.0.0"
pnet = "0.35.0"
tokio = "1.38.0"



# [build-dependencies]
# libloading = "0.8"
# regex = "1"
# pkg-config = "0.3"
